export const jobRoles = [
  "Administrative Assistant",
  "Receptionist",
  "Office Manager",
  "Executive Assistant",
  "Data Entry Clerk",
  "Marketing Executive",
  "Digital Marketing Specialist",
  "Sales Representative",
  "Business Development Executive",
  "Content Writer / Copywriter",
  "SEO Specialist",
  "Customer Service Representative",
  "Call Center Agent",
  "Technical Support Specialist",
  "Client Success Manager",
  "Accountant",
  "Finance Analyst",
  "Accounts Payable/Receivable Clerk",
  "Payroll Specialist",
  "Auditor",
  "HR Executive",
  "Recruiter / Talent Acquisition Specialist",
  "HR Manager",
  "Training & Development Coordinator",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "DevOps Engineer",
  "UI/UX Designer",
  "IT Support Specialist",
  "QA Engineer",
  "Operations Executive",
  "Supply Chain Analyst",
  "Logistics Coordinator",
  "Inventory Manager",
  "Team Lead",
  "Project Manager",
  "Product Manager",
  "Operations Manager",
  "General Manager",
  "Graphic Designer",
  "Video Editor",
  "Animator",
  "Creative Director",
  "Analyst (e.g., Business Analyst, Data Analyst)",
  "Consultant",
  "Trainer",
  "Field Executive",
  "Intern / Trainee"
];
